const SUBSCRIBE_TO_STORY_BY_RANK = "SUBSCRIBE_TO_STORY_BY_RANK";
const SUBSCRIBE_TO_STORY_BY_RANK_SUCCESS = "SUBSCRIBE_TO_STORY_BY_RANK_SUCCESS";
const SUBSCRIBE_TO_STORY_BY_RANK_CANCEL = "SUBSCRIBE_TO_STORY_BY_RANK_CANCEL";
const SUBSCRIBE_TO_STORY_BY_RANK_FAILURE = "SUBSCRIBE_TO_STORY_BY_RANK_FAILURE";

export default {
  SUBSCRIBE_TO_STORY_BY_RANK,
  SUBSCRIBE_TO_STORY_BY_RANK_SUCCESS,
  SUBSCRIBE_TO_STORY_BY_RANK_CANCEL,
  SUBSCRIBE_TO_STORY_BY_RANK_FAILURE
};
