const SUBSCRIBE_TO_ITEM_BY_ID = "SUBSCRIBE_TO_ITEM_BY_ID";
const SUBSCRIBE_TO_ITEM_BY_ID_SUCCESS = "SUBSCRIBE_TO_ITEM_BY_ID_SUCCESS";
const SUBSCRIBE_TO_ITEM_BY_ID_CANCEL = "SUBSCRIBE_TO_ITEM_BY_ID_CANCEL";
const SUBSCRIBE_TO_ITEM_BY_ID_FAILURE = "SUBSCRIBE_TO_ITEM_BY_ID_FAILURE";

export default {
  SUBSCRIBE_TO_ITEM_BY_ID,
  SUBSCRIBE_TO_ITEM_BY_ID_SUCCESS,
  SUBSCRIBE_TO_ITEM_BY_ID_CANCEL,
  SUBSCRIBE_TO_ITEM_BY_ID_FAILURE
};



